### ISSUE TITLE
HecDss.open() Instead of DSS.open()

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/DSSVue-Example-Scripts#3]
Should we be demonstrating the use of HecDss.open() instead of DSS.open()?

https://github.com/HydrologicEngineeringCenter/DSSVue-Ch8-Example-Scripts/blob/4d9cb5abccfc67611e084b58e7851e6f71cd0f45/AddTenHecMath.py#L13

**Comment by ktarbet** [comment]
I agree, the document says use HecDss
https://www.hec.usace.army.mil/confluence/dssvuedocs/latest/chapter8-scripting/reading-and-writing-to-hec-dss-files

**Comment by Tich1212** [comment]
Closing with this commit f7268755607eaf4d1d62defd55b469228f886226
