### ISSUE TITLE
change default import statements

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/DSSVue-Example-Scripts#6]
Related to issue #5 

Since wildcard imports do not work anymore we should change the default import statements when creating a new script.

![image](https://user-images.githubusercontent.com/57423836/79595365-8d74a080-8093-11ea-80f2-9a1e3219e854.png)

**Comment by ktarbet** [comment]
closing.  Here is the new import.

```java
    public static final String STD_IMPORT = "from hec.script import Plot\n"
                                          + "#from hec.io import TimeSeriesContainer\n"
                                          + "#from hec.io import PairedDataContainer\n"
                                          + "#from hec.io import TimeSeriesMath\n"
                                          + "#from hec.io import PairedDataMath\n"
                                        ;

	public static final String DSS_IMPORT = "from hec.heclib.dss import HecDss\n";
	public static final String JAVA_IMPORT = "#import java\n";

```

**Comment by Tich1212** [comment]
> closing. Here is the new import.
> 
> ```java
>     public static final String STD_IMPORT = "from hec.script import Plot\n"
>                                           + "#from hec.io import TimeSeriesContainer\n"
>                                           + "#from hec.io import PairedDataContainer\n"
>                                           + "#from hec.io import TimeSeriesMath\n"
>                                           + "#from hec.io import PairedDataMath\n"
>                                         ;
> 
> 	public static final String DSS_IMPORT = "from hec.heclib.dss import HecDss\n";
> 	public static final String JAVA_IMPORT = "#import java\n";
> ```

TimeSeriesMath and PairedDataMath should be imported from hec.hecmath:

`from hec.hecmath import TimeSeriesMath`
`from hec.hecmath import PairedDataMath`

Also seems like a good idea to import DSSPathname by Default:

`from hec.heclib.dss import HecDss, DSSPathname`

**Comment by ktarbet** [comment]
@Tich1212  
How does this look?
```Java
from hec.script import Plot
#from hec.io import TimeSeriesContainer
#from hec.io import PairedDataContainer
#from hec.hecmath import TimeSeriesMath
#from hec.hecmath import PairedDataMath
from hec.heclib.dss import HecDss, DSSPathname
#import java

**Comment by Tich1212** [comment]
Looks good.
